06-11-2024/Models/Film.cs
namespace _06_11_2024.Models
{
	public class Film
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Director { get; set; }
		public string Jenre { get; set; }
		public string Description { get; set; }
		public List<Session>? Sessions { get; set; }
	}
}

06-11-2024/Models/Session.cs
namespace _06_11_2024.Models
{
	public class Session
	{
		public int Id { get; set; }
		public DateOnly Date { get; set; }
	}
}

06-11-2024/Pages/Edit.cshtml.cs
using _06_11_2024.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _06_11_2024.Pages
{
	public class EditModel(ApplicationContext context) : PageModel
	{
		private ApplicationContext context = context;
		public Film film;

		public void OnGet(int id)
		{
			if (id != 0)
				film = context.Films.First(f => f.Id == id);
			else
			{
				film = new()
				{
					Name = "",
					Director = "",
					Description = "",
					Jenre = "",
					Sessions = []
				};
			}
		}
		public IActionResult OnPost(int id, string name, string director, string description, string jenre)
		{
			if (id != 0)
				film = context.Films.First(f => f.Id == id);
			else
				film = new()
				{
					Sessions = []
				};

			film.Name = name;
			film.Director = director;
			film.Description = description;
			film.Jenre = jenre;

			if (id != 0)
				context.SaveChanges();
			else
			{
				context.Films.Add(film);
				context.SaveChanges();
			}
			return RedirectToPage("Index");
		}
	}
}

06-11-2024/Pages/Film.cshtml.cs
using _06_11_2024.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace _06_11_2024.Pages
{
	public class FilmModel(ApplicationContext context) : PageModel
	{
		private ApplicationContext context = context;
		public Film film;

		public void OnGet(int id)
		{
			film = context.Films.Include(f => f.Sessions).First(f => f.Id == id);
		}

		public IActionResult OnGetDelete(int id)
		{
			film = context.Films.Include(f => f.Sessions).First(f => f.Id == id);
			context.Films.Remove(film);
			context.SaveChanges();
			return RedirectToPage("Index");
		}

		public IActionResult OnPostAddSession(int id, DateOnly date)
		{
			Session session = new() { Date = date };
			context.Sessions.Add(session);
			film = context.Films.Include(f => f.Sessions).First(f => f.Id == id);
			film.Sessions ??= [];
			film.Sessions.Add(session);
			context.SaveChanges();
			return RedirectToPage("Film", new { id });
		}
	}
}

06-11-2024/Pages/Index.cshtml.cs
using _06_11_2024.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace _06_11_2024.Pages
{
	public class IndexModel(ApplicationContext context) : PageModel
	{
		private ApplicationContext context = context;
		public List<Film> films;
		public bool fullList;

		public void OnGet(string? search)
		{
			films = [.. context.Films.Include(f => f.Sessions)];
			if (search is not null)
			{
				search = search.ToLower();
				films = films.Where(f => f.Name.ToLower().Contains(search)
				|| f.Jenre.ToLower().Contains(search)
				|| f.Director.ToLower().Contains(search)
				|| f.Description.ToLower().Contains(search)).ToList();
				fullList = false;
			}
			else
				fullList = true;
		}
	}
}

06-11-2024/Pages/Edit.cshtml
@page
@model _06_11_2024.Pages.EditModel

<div class="row mt-3">
	<div class="col-6 offset-3">
		<form asp-page="Edit" method="post">
			<input type="hidden" name="id" value="@Model.film.Id" />
			<div class="row">
				<div class="col-3">
					<label for="Name" class="form-label">Название</label>
				</div>
				<div class="col-9">
					<input class="form-control" type="text" name="name" value="@Model.film.Name" />
				</div>
			</div>
			<div class="row">
				<div class="col-3">
					<label for="Director" class="form-label">Режиссёр</label>
				</div>
				<div class="col-9">
					<input class="form-control" type="text" name="director" value="@Model.film.Director" />
				</div>
			</div>
			<div class="row">
				<div class="col-3">
					<label for="Jenre" class="form-label">Жанр</label>
				</div>
				<div class="col-9">
					<input class="form-control" type="text" name="jenre" value="@Model.film.Jenre" />
				</div>
			</div>
			<div class="row">
				<div class="col-3">
					<label for="Description" class="form-label">Описание</label>
				</div>
				<div class="col-9">
					<input class="form-control" type="text" name="description" value="@Model.film.Description" />
				</div>
			</div>
			<div class="row">
				<input class="btn-primary" type="submit" value="Сохранить" />
			</div>
		</form>
	</div>
</div>

06-11-2024/Pages/Film.cshtml
@page
@model _06_11_2024.Pages.FilmModel

<div class="row mt-3">
	<div class="col">
		<a asp-page="Index">Назад</a>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th scope="col">Название</th>
					<th scope="col">Режиссер</th>
					<th scope="col">Жанр</th>
					<th scope="col">Краткое описание</th>
					<th scope="col">Список сеансов</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>@Model.film.Name</td>
					<td>@Model.film.Director</td>
					<td>@Model.film.Jenre</td>
					<td>@Model.film.Description</td>
					<td>
						@if (Model.film.Sessions is not null)
							@foreach (var s in Model.film.Sessions)
							{
								<div>@s.Date.ToShortDateString()</div>
							}
					</td>
					<td>
						<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#sessionModal">
							Добавить сеанс
						</button>
					</td>
					<td>
						<a asp-page="Edit" asp-route-id=@Model.film.Id>
							Редактировать
						</a>
					<td>
						<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteModal">
							Удалить
						</button>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="modal fade" id="sessionModal" tabindex="-1" aria-labelledby="sessionModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<form method="post" asp-page-handler="AddSession">
						<div class="modal-header">
							<h1 class="modal-title fs-5" id="sessionModalLabel">Выберите дату сеанса</h1>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
						</div>
						<div class="modal-body">
							<input type="hidden" name="id" value="@Model.film.Id" />
							<input class="form-control" type="date" name="date" />
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Нет, не надо</button>
							<button type="submit" class="btn btn-primary">Да, добавить</button>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h1 class="modal-title fs-5" id="deleteModalLabel">Действительно удалить?</h1>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Нет, погодите</button>
						<a asp-page-handler="Delete" asp-route-id=@Model.film.Id>Да, удалить</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

06-11-2024/Pages/Index.cshtml
@page
@model IndexModel

<div class="row mt-3">
	<div class="col-6 offset-3">
		<form action="/" method="get">
			<div class="row">
				<div class="col-9">
					<input type="text" name="search" class="form-control w-100" placeholder="Введите название для поиска" />
				</div>
				<div class="col-3">
					<input type="submit" value="Найти" class="btn btn-primary w-100" />
				</div>
			</div>
		</form>
		@if (!Model.fullList)
		{
			<div class="row mt-3">
				<a asp-page="Index">Вернуться к полному списку</a>
			</div>
		}
		<table class="table table-striped table-bordered mt-3">
			<thead>
				<tr>
					<th scope="col">Название</th>
					<th scope="col">Список сеансов</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var f in Model.films)
				{
					<tr>
						<td><a asp-page="Film" , asp-route-id="@f.Id">@f.Name</a></td>
						<td>
							@if (f.Sessions is not null)
								@foreach (var s in f.Sessions)
								{
									<div>@s.Date.ToShortDateString()</div>
								}
						</td>
					</tr>
				}
			</tbody>
		</table>
		<div class="row mt-3">
			<a asp-page="Edit" asp-route-id=0>Добавить</a>
		</div>
	</div>
</div>

06-11-2024/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - _06_11_2024</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/_06_11_2024.styles.css" asp-append-version="true" />
</head>
<body>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>